- name: first playbook
  hosts: all
  become: yes
  tasks:
    - name: install httpd process
      yum:
        name: httpd
        state: latest
    - name: start web server
      service: 
        name: httpd
        state: started
    - name: copy the index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: restart httpd
      service:
        name: httpd
        state: restarted
