#In Ansible, handlers are used to run tasks only when something changes. They are mainly used for actions like restart service, reload config, restart app.
#Think of handlers as event-based tasks.


- name: first playbook
  hosts: all
  become: yes
  tasks:
    - name: install httpd software
      yum:
        name: httpd
        state: latest
    - name: start web server
      service:
        name: httpd
        state: started
    - name: copying the files
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify: Restart web server
  handlers:
    - name: Restart web server
      service:
        name: httpd
        state: restarted
