- name: copy playbook
  hosts: all
  become: yes
  vars: 
    - a: httpd
    - b: present
    - c: started
    - d: restarted

  tasks:
    - name: install httpd software
      yum:
        name: "{{a}}"
        state: "{{b}}"
    - name: start httpd server
      service:
        name: "{{a}}"
        state: "{{c}}"
    - name: copying the files
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: restart the httpd server
      service:
        name: "{{a}}"
        state: "{{d}}"
